apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlvr-auth
  namespace: dlvr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dlvr-auth
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dlvr-auth
    spec:
      containers:
      - name: dlvr-auth
        image: vidurkhanal/dlvr-auth
        envFrom:
          - configMapRef:
              name: dlvr-auth-config
          - secretRef:
              name: dlvr-auth-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8060
